// Post exercises
###
POST http://localhost:3003/exercises HTTP/1.1
Content-Type: application/json

{
  "dailyExerciseHours": [1, 0, 2, 0, 3, 0, 2.5],
  "targetAmount": 2.5
}

// Post exercises
###
POST http://localhost:3003/exercises HTTP/1.1
Content-Type: application/json

{
  "dailyExerciseHours": [1, 0, 2, 0, 3, 0, 2.5]
}

// Post exercises
###
POST http://localhost:3003/exercises HTTP/1.1
Content-Type: application/json

{
  "targetAmount": 2.5
}

// Post exercises
###
POST http://localhost:3003/exercises HTTP/1.1
Content-Type: application/json

{
  "dailyExerciseHours": [1, 0, 2, 0, 3, 0, 2.5],
  "targetAmount": "lol"
}

// Post exercises
###
POST http://localhost:3003/exercises HTTP/1.1
Content-Type: application/json

{
  "dailyExerciseHours": [1, "lol", 2, 0, 3, 0, 2.5],
  "targetAmount": 2.5
}