// Delete person
DELETE https://fso-phonebook-wjnd.onrender.com/api/persons/64af712eb272b14c191c4a0a

// Add person
###
POST https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{ 
  "name": "Liss Serrano", 
  "number": "34-445323523"
}

// Check empyty name
###
POST https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "",
  "number": "34-123456"
}

// Check empyty number
###
POST https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Xavi",
  "number": ""
}

// Check Existing person
###
POST https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "34-123456"
}

// Get phonebook
###
GET https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1

// Check non existing person
###
GET https://fso-phonebook-wjnd.onrender.com/api/persons/64b0be6dd7e92b8c9954f42r HTTP/1.1

// Update person number
###
PUT https://fso-phonebook-wjnd.onrender.com/api/persons/64b0be6dd7e92b8c9954f42c HTTP/1.1
Content-Type: application/json

{ 
  "name": "Liss Serrano", 
  "number": "69-445323523"
}