DELETE https://fso-phonebook-wjnd.onrender.com/api/persons/2

###
POST https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Joan Serrano",
  "number": "34-123456"
}

###
POST https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "",
  "number": "34-123456"
}

###
POST https://fso-phonebook-wjnd.onrender.com/api/persons HTTP/1.1
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "34-123456"
}

###
GET https://fso-phonebook-wjnd.onrender.com/api/persons